### ISSUE TITLE
Make repo publish

### ISSUE THREAD

**Issue by mikkoh** [Shopify/babel-plugin-add-header-comment#1]
@Shopify/javascript would you please take a look at this Babel Plugin. I'd like to make this repo  public and push it to npm. 

The idea is to build on top of this plugin and make https://github.com/Shopify/babel-plugin-add-shopify-header

This would allow for Babel to drop in a default header on all distributable JS files.

**Comment by lemonmade** [comment]
You can see how we typically structure things in the core repo (https://github.com/Shopify/shopify/blob/master/test/javascripts/unit/async-require-test.js is a reasonable example). Note that they use suite/ test, but same idea as describe/ it.
